language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

# faster builds on new travis setup not using sudo
#sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: hhvm-nightly

services:
  - redis-server
  - memcached
  - mongodb

addons:
  apt:
    sources:
      - couchbase-precise
    packages:
      - autoconf
      - libcouchbase-dev
      - libcouchbase2-libevent
      - libtool
      - php-pear
      - php5-dev

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist
  - travis_retry composer require satooshi/php-coveralls:*@dev
  - chmod -R +x tests/data/travis/
  - tests/data/travis/apc-setup.sh
  - tests/data/travis/memcache-setup.sh
  - tests/data/travis/redis-setup.sh
  - tests/data/travis/couchbase-setup.sh
  - tests/data/travis/mongodb-setup.sh

before_script:
  - mongo rocktest --eval 'db.addUser("travis", "test");'

script:
  - mkdir -p build/logs
  - |
    if (php --version | grep -i HipHop > /dev/null); then
      vendor/bin/phpunit --verbose --exclude-group php,redis,apc,couchbase,mongodb
    else
      vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml --exclude-group hhvm
    fi

after_script:
  - vendor/bin/coveralls -v
