sudo: required

env:
  - DOCKERFILE=php_54
  - DOCKERFILE=php_55
  - DOCKERFILE=php_56

services:
  - docker

before_install:
  - docker build -f $DOCKERFILE -t rock-cache .
  - docker run --name couchbase -d couchbase/server:community-3.0.1
  - docker run --name redis -d romeoz/docker-redis:2.8
  - docker run --name memcached -d romeoz/docker-memcached
  - docker run --name mongodb -d romeoz/docker-mongodb:2.6 --smallfiles --noprealloc
  - docker run --name app -d -e TRAVIS=$TRAVIS -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID --link couchbase:couchbase --link redis:redis --link memcached:memcached --link mongodb:mongodb -v $(pwd):/var/www rock-cache
  - docker ps -a

install:
  - chmod -R +x tests/data/travis/
  - travis_retry docker exec -it couchbase bash -c '/opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=default --bucket-type=memcached --bucket-ramsize=64 --enable-flush=1 -u demo -p demo'
  - tests/data/travis/mongodb-setup.sh
  - travis_retry docker exec -it app bash -c 'composer install --prefer-dist && composer require satooshi/php-coveralls:*@dev && mkdir -p build/logs'

script:
  - docker exec -it app bash -c 'vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml --exclude-group hhvm && vendor/bin/coveralls -v'
